CREATE DATABASE QAComp;
USE DATABASE QAComp;
CREATE TABLE product (
  id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
  name VARCHAR(50) NOT NULL,
  url VARCHAR(255) NOT NULL,
  price INT NOT NULL,
  description VARCHAR(255) NOT NULL,
  category VARCHAR(50) NOT NULL,
  vendor VARCHAR(50) NOT NULL,
  stars INT NOT NULL,
  size VARCHAR (20)
)