module.exports = {
  texts: [
    {
      id: 1,
      profileName: 'Zach Yusuf',
      subjectLine: 'Subject Line',
      location: 'United States',
      date: 'April 30th, 2020',
      itemDescription: 'Item Description',
      rating: 4,
      text: "For the price around 30 bucks and comparing it to others at the same price I give it 5 stars. Now if you compare it to a 300 hundred dollar lens I'd give it 2 stars. This isn't the lens for the wedding or professional photographer, I mean come on it's 30 bucks what did you think? It's for people like me who love photography but are on a budget. If I had the money of course I'd buy expensive ones but that isn't an option. I have noticed blurry edges around some landscape photos that can be cropped out. All I can say is that for 1/10th the price I can take some nice wide angle shots. Overall very happy with the lens.",
    },
    {
      id: 2,
      profileName: 'Zach Yusuf',
      subjectLine: 'Subject Line',
      location: 'United States',
      date: 'April 30th, 2020',
      itemDescription: 'Item Description',
      rating: 2,
      text: "For the price around 30 bucks and comparing it to others at the same price I give it 5 stars. Now if you compare it to a 300 hundred dollar lens I'd give it 2 stars. This isn't the lens for the wedding or professional photographer, I mean come on it's 30 bucks what did you think? It's for people like me who love photography but are on a budget. If I had the money of course I'd buy expensive ones but that isn't an option. I have noticed blurry edges around some landscape photos that can be cropped out. All I can say is that for 1/10th the price I can take some nice wide angle shots. Overall very happy with the lens.",
    },
    {
      id: 3,
      profileName: 'Zach Yusuf',
      subjectLine: 'Subject Line',
      location: 'United States',
      date: 'April 30th, 2020',
      itemDescription: 'Item Description',
      rating: 5,
      text: "For the price around 30 bucks and comparing it to others at the same price I give it 5 stars. Now if you compare it to a 300 hundred dollar lens I'd give it 2 stars. This isn't the lens for the wedding or professional photographer, I mean come on it's 30 bucks what did you think? It's for people like me who love photography but are on a budget. If I had the money of course I'd buy expensive ones but that isn't an option. I have noticed blurry edges around some landscape photos that can be cropped out. All I can say is that for 1/10th the price I can take some nice wide angle shots. Overall very happy with the lens.",
    },
    {
      id: 4,
      profileName: 'Zach Yusuf',
      subjectLine: 'Subject Line',
      location: 'United States',
      date: 'April 30th, 2020',
      itemDescription: 'Item Description',
      rating: 5,
      text: "For the price around 30 bucks and comparing it to others at the same price I give it 5 stars. Now if you compare it to a 300 hundred dollar lens I'd give it 2 stars. This isn't the lens for the wedding or professional photographer, I mean come on it's 30 bucks what did you think? It's for people like me who love photography but are on a budget. If I had the money of course I'd buy expensive ones but that isn't an option. I have noticed blurry edges around some landscape photos that can be cropped out. All I can say is that for 1/10th the price I can take some nice wide angle shots. Overall very happy with the lens.",
    },
    {
      id: 5,
      profileName: 'Zach Yusuf',
      subjectLine: 'Subject Line',
      location: 'United States',
      date: 'April 30th, 2020',
      itemDescription: 'Item Description',
      rating: 4,
      text: "For the price around 30 bucks and comparing it to others at the same price I give it 5 stars. Now if you compare it to a 300 hundred dollar lens I'd give it 2 stars. This isn't the lens for the wedding or professional photographer, I mean come on it's 30 bucks what did you think? It's for people like me who love photography but are on a budget. If I had the money of course I'd buy expensive ones but that isn't an option. I have noticed blurry edges around some landscape photos that can be cropped out. All I can say is that for 1/10th the price I can take some nice wide angle shots. Overall very happy with the lens.",
    },
    {
      id: 6,
      profileName: 'Zach Yusuf',
      subjectLine: 'Subject Line',
      location: 'United States',
      date: 'April 30th, 2020',
      itemDescription: 'Item Description',
      rating: 5,
      text: "For the price around 30 bucks and comparing it to others at the same price I give it 5 stars. Now if you compare it to a 300 hundred dollar lens I'd give it 2 stars. This isn't the lens for the wedding or professional photographer, I mean come on it's 30 bucks what did you think? It's for people like me who love photography but are on a budget. If I had the money of course I'd buy expensive ones but that isn't an option. I have noticed blurry edges around some landscape photos that can be cropped out. All I can say is that for 1/10th the price I can take some nice wide angle shots. Overall very happy with the lens.",
    },
    {
      id: 7,
      profileName: 'Zach Yusuf',
      subjectLine: 'Subject Line',
      location: 'United States',
      date: 'April 30th, 2020',
      itemDescription: 'Item Description',
      rating: 3,
      text: "For the price around 30 bucks and comparing it to others at the same price I give it 5 stars. Now if you compare it to a 300 hundred dollar lens I'd give it 2 stars. This isn't the lens for the wedding or professional photographer, I mean come on it's 30 bucks what did you think? It's for people like me who love photography but are on a budget. If I had the money of course I'd buy expensive ones but that isn't an option. I have noticed blurry edges around some landscape photos that can be cropped out. All I can say is that for 1/10th the price I can take some nice wide angle shots. Overall very happy with the lens.",
    },
    {
      id: 8,
      profileName: 'Zach Yusuf',
      subjectLine: 'Subject Line',
      location: 'United States',
      date: 'April 30th, 2020',
      itemDescription: 'Item Description',
      rating: 5,
      text: "For the price around 30 bucks and comparing it to others at the same price I give it 5 stars. Now if you compare it to a 300 hundred dollar lens I'd give it 2 stars. This isn't the lens for the wedding or professional photographer, I mean come on it's 30 bucks what did you think? It's for people like me who love photography but are on a budget. If I had the money of course I'd buy expensive ones but that isn't an option. I have noticed blurry edges around some landscape photos that can be cropped out. All I can say is that for 1/10th the price I can take some nice wide angle shots. Overall very happy with the lens.",
    },
  ],
};
