module.exports = {
  texting: [
    {
      id: 1,
      profileName: 'ZOObare',
      subjectLine: 'Best water bottle for hiking!',
      location: 'United States',
      date: 'November 30th, 2019',
      itemDescription: 'BlenderBottle Classic Loop Top Shaker Bottle',
      rating: 4,
      helpful: 1034,
      text: "For the price around 30 bucks and comparing it to others at the same price I give it 5 stars. Now if you compare it to a 300 hundred dollar lens I'd give it 2 stars. This isn't the lens for the wedding or professional photographer, I mean come on it's 30 bucks what did you think? It's for people like me who love photography but are on a budget. If I had the money of course I'd buy expensive ones but that isn't an option. I have noticed blurry edges around some landscape photos that can be cropped out. All I can say is that for 1/10th the price I can take some nice wide angle shots. Overall very happy with the lens.",
    },
    {
      id: 2,
      profileName: 'LauraEvandro',
      subjectLine: "Where's my bottle?!",
      location: 'United States',
      date: 'September 15th, 2019',
      itemDescription: 'BlenderBottle Radian Insulated Stainless Steel Shaker Bottle',
      rating: 2,
      helpful: 13,
      text: "For the price around 30 bucks and comparing it to others at the same price I give it 5 stars. Now if you compare it to a 300 hundred dollar lens I'd give it 2 stars. This isn't the lens for the wedding or professional photographer, I mean come on it's 30 bucks what did you think? It's for people like me who love photography but are on a budget. If I had the money of course I'd buy expensive ones but that isn't an option. I have noticed blurry edges around some landscape photos that can be cropped out. All I can say is that for 1/10th the price I can take some nice wide angle shots. Overall very happy with the lens.",
    },
    {
      id: 3,
      profileName: 'CollinsWasHere',
      subjectLine: 'Best christmas presents ever',
      location: 'United States',
      date: 'August 29th, 2019',
      itemDescription: 'BlenderBottle Mantra Glass Shaker Bottle',
      rating: 5,
      helpful: 1734,
      text: "For the price around 30 bucks and comparing it to others at the same price I give it 5 stars. Now if you compare it to a 300 hundred dollar lens I'd give it 2 stars. This isn't the lens for the wedding or professional photographer, I mean come on it's 30 bucks what did you think? It's for people like me who love photography but are on a budget. If I had the money of course I'd buy expensive ones but that isn't an option. I have noticed blurry edges around some landscape photos that can be cropped out. All I can say is that for 1/10th the price I can take some nice wide angle shots. Overall very happy with the lens.",
    },
    {
      id: 4,
      profileName: 'Gjoker94',
      subjectLine: 'Keeps me hydrated',
      location: 'United States',
      date: 'July 7th, 2019',
      itemDescription: 'BlenderBottle SportMixer Twist Cap Tritan Grip Shaker Bottle',
      rating: 5,
      helpful: 1,
      text: "For the price around 30 bucks and comparing it to others at the same price I give it 5 stars. Now if you compare it to a 300 hundred dollar lens I'd give it 2 stars. This isn't the lens for the wedding or professional photographer, I mean come on it's 30 bucks what did you think? It's for people like me who love photography but are on a budget. If I had the money of course I'd buy expensive ones but that isn't an option. I have noticed blurry edges around some landscape photos that can be cropped out. All I can say is that for 1/10th the price I can take some nice wide angle shots. Overall very happy with the lens.",
    },
    {
      id: 5,
      profileName: 'DANTE',
      subjectLine: 'Who makes a bottle this cool?',
      location: 'United States',
      date: 'June 30th, 2019',
      itemDescription: 'BlenderBottle ProStak System with 22-Ounce Bottle and Twist n Lock Storage',
      rating: 4,
      helpful: 170,
      text: "For the price around 30 bucks and comparing it to others at the same price I give it 5 stars. Now if you compare it to a 300 hundred dollar lens I'd give it 2 stars. This isn't the lens for the wedding or professional photographer, I mean come on it's 30 bucks what did you think? It's for people like me who love photography but are on a budget. If I had the money of course I'd buy expensive ones but that isn't an option. I have noticed blurry edges around some landscape photos that can be cropped out. All I can say is that for 1/10th the price I can take some nice wide angle shots. Overall very happy with the lens.",
    },
    {
      id: 6,
      profileName: 'nitram somar',
      subjectLine: 'I named my bottle martin Jr',
      location: 'United States',
      date: 'April 30th, 2019',
      itemDescription: 'BlenderBottle ProStak System with 22-Ounce Bottle and Twist n Lock Storage',
      rating: 5,
      helpful: 173,
      text: "For the price around 30 bucks and comparing it to others at the same price I give it 5 stars. Now if you compare it to a 300 hundred dollar lens I'd give it 2 stars. This isn't the lens for the wedding or professional photographer, I mean come on it's 30 bucks what did you think? It's for people like me who love photography but are on a budget. If I had the money of course I'd buy expensive ones but that isn't an option. I have noticed blurry edges around some landscape photos that can be cropped out. All I can say is that for 1/10th the price I can take some nice wide angle shots. Overall very happy with the lens.",
    },
    {
      id: 7,
      profileName: 'OvoPoli',
      subjectLine: 'This bottle took out my wisdom teeth',
      location: 'United States',
      date: 'March 30th, 2019',
      itemDescription: 'BlenderBottle Mantra Glass Shaker Bottle',
      rating: 1,
      helpful: 234,
      text: "For the price around 30 bucks and comparing it to others at the same price I give it 5 stars. Now if you compare it to a 300 hundred dollar lens I'd give it 2 stars. This isn't the lens for the wedding or professional photographer, I mean come on it's 30 bucks what did you think? It's for people like me who love photography but are on a budget. If I had the money of course I'd buy expensive ones but that isn't an option. I have noticed blurry edges around some landscape photos that can be cropped out. All I can say is that for 1/10th the price I can take some nice wide angle shots. Overall very happy with the lens.",
    },
    {
      id: 8,
      profileName: 'Zach Yusuf',
      subjectLine: 'Subject Line',
      location: 'United States',
      date: 'April 30th, 2020',
      itemDescription: 'Item Description',
      rating: 5,
      helpful: 134,
      text: "For the price around 30 bucks and comparing it to others at the same price I give it 5 stars. Now if you compare it to a 300 hundred dollar lens I'd give it 2 stars. This isn't the lens for the wedding or professional photographer, I mean come on it's 30 bucks what did you think? It's for people like me who love photography but are on a budget. If I had the money of course I'd buy expensive ones but that isn't an option. I have noticed blurry edges around some landscape photos that can be cropped out. All I can say is that for 1/10th the price I can take some nice wide angle shots. Overall very happy with the lens.",
    },
  ],
};
